set(CPACK_PACKAGE_NAME ${PROJECT_NAME}
    CACHE STRING "The resulting package name"
)

set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "C++ library"
    CACHE STRING "Package description for the package metadata"
)

set(CPACK_PACKAGE_VENDOR "ALLOMOWING")
set(CPACK_PACKAGE_CONTACT "stroalgo@gmail.com")

set(CPACK_PACKAGE_VERSION_MAJOR ${PROJECT_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PROJECT_VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PROJECT_VERSION_PATCH})

SET(CPACK_PACKAGE_DIRECTORY "${CMAKE_SOURCE_DIR}/_PACKAGE_")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "ALLOMOWING")
set(CPACK_VERBATIM_VARIABLES YES)

set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")